### ISSUE TITLE
DIANN and data process

### ISSUE THREAD

**Issue by gcrynen** [Vitek-Lab/MSstatsConvert#76]
Hi,
I am trying to analyze DIA-NN results with MsStats but I have been having some problems. I think the problem stems from having multiple modified sequences per Stripped sequence.  I realize msconvert should reduce the sequence number per stripped peptide to 1 but it seems like I am not getting that effect. Am I doing something wrong? before the most recent update I had problems with running DIANNtoMSstatsFormat but now it is running without error/warning messages.
I am using:
R version 4.2.3 (2023-03-15 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)
data.table_1.14.8     MSstatsConvert_1.11.1 MSstats_4.9.2 

library(MSstats)
library(MSstatsConvert)
library(data.table)
input <- data.table::fread('DDAdbauto_libfreesearchv2_89proteins.tsv')
annot <- data.table::fread('annotation_diann.csv')
colnames(annot) <- c('FileName', 'Condition','BioReplicate','Run')

MS222048_LB<-DIANNtoMSstatsFormat(input, annotation = annot, MBR = TRUE)
DIAquant<-dataProcess(MS222048_LB)
But I get the following error. 
INFO  [2023-06-26 15:28:46] ** Log2 intensities under cutoff = 8.4843  were considered as censored missing values.
INFO  [2023-06-26 15:28:46] ** Log2 intensities = NA were considered as censored missing values.
INFO  [2023-06-26 15:28:46] ** Use all features that the dataset originally has.
INFO  [2023-06-26 15:28:46] 
 # proteins: 8
 # peptides per protein: 2-24
 # features per peptide: 1-1
INFO  [2023-06-26 15:28:46] 
                    FC FE MC ME
             # runs  6  6  6  6
    # bioreplicates  6  6  6  6
 # tech. replicates  1  1  1  1
INFO  [2023-06-26 15:28:46]  == Start the summarization per subplot...
  |                                                                   |   0%Aggregate function missing, defaulting to 'length'
<simpleError in .Primitive("length")(newABUNDANCE, keep = TRUE): 2 arguments passed to 'length' which requires 1>
INFO  [2023-06-26 15:28:46]  == Summarization is done.
Error in merge.data.table(input[, colnames(input) != "newABUNDANCE", with = FALSE],  : 
  Elements listed in `by` must be valid column names in x and y
In addition: Warning message:
In merge.data.table(input[, colnames(input) != "newABUNDANCE", with = FALSE],  :
  You are trying to join data.tables where 'y' argument is 0 columns data.table.
I am attaching the example files here.
Thank you very much.
[MSstats.zip](https://github.com/Vitek-Lab/MSstatsConvert/files/11873382/MSstats.zip)

**Comment by mstaniak** [comment]
Hi,
is this a fractionated experiment?

**Comment by gcrynen** [comment]
No, it  includes individual runs for each sample. in short, one run per biological replicate.

**Comment by mstaniak** [comment]
Thanks for a quick answer, I had a problem with reproducing the issue, but now it's OK, I should have a solution soon

**Comment by mstaniak** [comment]
Hi,
my apologies, it was a problem with Sequence column selection.
Please run this code before running dataProcess:

`
MS222048_LB = as.data.table(MS222048_LB)
MS222048_LB[, PeptideSequence := NULL]
setnames(MS222048_LB, "PeptideModifiedSequence", "PeptideSequence")
`
and I will make it a default behavior in MSstats in next update. Please let me know if you were able to run the analysis after this fix.

**Comment by gcrynen** [comment]
Hi,
it works! I will try in the larger dataset.
Thank you for very speedy solution. I really appreciate it.
