### ISSUE TITLE
DIANN converter: Cannot detect PeptideModifiedSequence in input columns

### ISSUE THREAD

**Issue by She1111** [Vitek-Lab/MSstatsConvert#80]
Hi,

I used ```DIANNtoMSstatsFormat``` to convert ```report.tsv``` from DIA-NN. I noticed converter cannot detect ```PeptideModifiedSequence```. Follow the code and log file.

```
report_TrP <- fread("C:/Learning/0-Data/report.tsv")
annot_TrP <- read.csv("C:/Learning/0-Data/annotation.csv")
report_TrP <- DIANNtoMSstatsFormat(report_TrP, annotation = annot_TrP)
```
[MSstats_log_2023_07_18_17_18_05.17348.log](https://github.com/Vitek-Lab/MSstatsConvert/files/12083031/MSstats_log_2023_07_18_17_18_05.17348.log)

**Comment by mstaniak** [comment]
is this column present in the input?

**Comment by She1111** [comment]
> is this column present in the input?

Yes. Because the file is too large to upload, here is screen shot of the file.
<img width="817" alt="Capture" src="https://github.com/Vitek-Lab/MSstatsConvert/assets/130647208/a75387db-e8e1-4a35-be7c-7bc5b4f595de">

**Comment by mstaniak** [comment]
please try changing "Modified.Sequence" to "Peptide.Modified.Sequence".
Is this a default column name? What version of DIA-NN did you use? I might need to add an option for this, example data I used had a different name for this column.

**Comment by She1111** [comment]
> please try changing "Modified.Sequence" to "Peptide.Modified.Sequence". Is this a default column name? What version of DIA-NN did you use? I might need to add an option for this, example data I used had a different name for this column.

Yes it is the default column name. I used ```DIA-NN 1.8.1```.

I run this code but it returns a error:
```report_TrP <- fread("C:/Learning/0-Data/report.tsv")
annot_TrP <- read.csv("C:/Learning/0-Data/annotation.csv")
colnames(report_TrP)[14] <- "Peptide.Modified.Sequence"
report_TrP <- DIANNtoMSstatsFormat(report_TrP, annotation = annot_TrP)```

```INFO  [2023-07-18 17:52:20] ** Raw data from DIANN imported successfully.
Error in `[.data.table`(dn_input, , req_cols, with = FALSE) : 
  column(s) not found: ModifiedSequence```

**Comment by mstaniak** [comment]
My bad, ModifiedSequence should be the column name, we change that to PeptideModifiedSequence internally. 

Currently, this warning only affects oxidation filtering. You can do it manually if needed.  Currently, our internal oxidation filter uses a wrong column name. I will update MSstats package to fix this, other than that everything should be OK.
I'm closing this issue, please re-open if needed. Also please let me know if you have other problems with the converter.

**Comment by mstaniak** [comment]
Requires MSstats update

**Comment by mstaniak** [comment]
Thanks for reporting the issue btw!

**Comment by She1111** [comment]
Thank you so much for your quick reply! :)

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by She1111** [comment]
Hi,

As I have two lists of data both have been converted from one DIA-NN file but in different data, one has been done on 2nd July and one on 19th July. They are different. Which one is the reliable one?

Thanks in advance!

Best regards,
Shel
[MSstats_log_2023_07_02_20_42_53.114015_previous.log](https://github.com/Vitek-Lab/MSstatsConvert/files/12148221/MSstats_log_2023_07_02_20_42_53.114015_previous.log)
[MSstats_log_2023_07_18_18_27_27.259128_latest.log](https://github.com/Vitek-Lab/MSstatsConvert/files/12148222/MSstats_log_2023_07_18_18_27_27.259128_latest.log)

**Comment by She1111** [comment]
> Current version. In the past the converter aggregated fragment ion information prematurely.

THANK YOU so much for your quickly reply and help! I am going to use the latest one for further MSstats analysis.

Cheers,
Shel

**Comment by She1111** [comment]
Hi,

I notice that ```DIANNtoMSstatsFormat``` will select ```Protein.Names``` in DIA-NN output file as ```ProteinName``` automatically which can not match with the information of proteins from Uniprot when I use MSstatsLiP package. Is it feasible to add an option for selecting presented columns? Or is it more convenient to just rename the column name in RAW datafile?
<img width="928" alt="MSstatsConvert" src="https://github.com/Vitek-Lab/MSstatsConvert/assets/130647208/c871493f-4d02-4ca5-8cf3-39d91d07fee2">

Thanks in advance!

Cheers,
Shel

**Comment by mstaniak** [comment]
For now, please rename the column. I will add that option in a few days, thanks for letting me know

**Comment by mstaniak** [comment]
Hi,
I thought I responded by e-mail, not sure if it went through. For now, please rename the column before using converter, I will add such a parameter to converter later.
